export const data: any = {ko_mapnotdefined : ["M - 1 - 1","M - 2 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mapnotcorrectone : ["C - A","M - 1 - 1","M - 2 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mapnotcorrecttwo : ["C - 2 - 3 - 4","M - 1 - 1","M - 2 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mapnotcorrectthree : ["C24","M - 1 - 1","M - 2 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mapdefinedandcorrect : ["C - 2 - 4","M - 1 - 1","M - 2 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ok_mountainnotdefined : ["C - 2 - 4","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mountainnotcorrectone :  ["C - 2 - 4","M - A","M - 2 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mountainnotcorrecttwo :  ["C - 2 - 4","M - 1 - 1","M - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_mountainnotcorrectthree :  ["C - 2 - 4","M - 1 - 1","M12","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ok_mountaincorrectanddefined :  ["C - 2 - 4","M - 1 - 1","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ok_mountainscorrectanddefined :  ["C - 2 - 4","M - 1 - 1","M - 1 - 2","T - 0 - 3 - 2","T - 1 - 3 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_tresournotdefined : ["C - 2 - 4","A - Indiana - 0 - 1 - S - AADADA"],
    ko_tresournotcorrect : ["C - 2 - 4","T - A","A - Indiana - 0 - 1 - S - AADADA"],
    ko_tresournotcorrecttwo : ["C - 2 - 4","T - 1 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_tresournotcorrectthree : ["C - 2 - 4","T234","T - 1 - 1 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_tresournotcorrectfour : ["C - 2 - 4","T - 1 - 1 - 1 - 4","A - Indiana - 0 - 1 - S - AADADA"],
    ok_tresourcorrect : ["C - 2 - 4","T - 1 - 1 - 4","A - Indiana - 0 - 1 - S - AADADA"],
    ok_tresourscorrect : ["C - 2 - 4","T - 1 - 1 - 4",,"T - 2 - 1 - 1","A - Indiana - 0 - 1 - S - AADADA"],
    ko_explorernotdefined : ["C - 2 - 4","T - 1 - 2 - 2"],
    ko_explorernotcorrectone : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - 0 - 1 - S"],
    ko_explorernotcorrecttwo : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - A - 1 - S - AAGADA"],
    ko_explorernotcorrectthree : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - 0 - B - S - AADADA"],
    ko_explorernotcorrectfour : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - 0 - 1 - G - AADADA"],
    ko_explorernotcorrectfive : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - 0 - 1 - S - AAVADA"],
    ko_explorernotcorrectsix : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A -     - 0 - 1 - S - AAGADA"],
    ok_explorercorrect : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - 0 - 1 - N - AADADA"],
    ok_explorerscorrect : ["C - 2 - 4","T - 1 - 2 - 2","T - 2 - 2 - 1","A - Indiana - 0 - 1 - N - AADADA", "A - Sophie - 1 - 1 - S - ADGADA"],
};